class Message {
  /// ID of the message
  final String id;

  /// ID of the sender
  final String profileId;
  final String content;
  final DateTime createdAt;

  /// Whether the message was sent by the user or received
  final bool sentByUser;

  /// Whether the message was generated by GenAI
  final bool generated;

  /// Whether the message was guessed correctly
  final bool correclyIdentified;

  Message({
    required this.id,
    required this.profileId,
    required this.content,
    required this.createdAt,
    required this.sentByUser,
    required this.generated,
    required this.correclyIdentified,
  });
}
