import 'package:supabase_api/supabase_api.dart' show MessageModel;

class Message {
  /// ID of the message
  final String id;

  /// ID of the sender
  final String profileId;
  final String content;
  final DateTime createdAt;

  /// Whether the message was sent by the user or received
  final bool sentByUser;


  /// Whether the message was generated by GenAI
  final bool generated;

  /// Whether the message was guessed correctly
  /// (is null if not guessed at all yet)
  final bool? correctlyIdentified;

  final bool sent;

  Message({
    required this.id,
    required this.profileId,
    required this.content,
    required this.createdAt,
    required this.sentByUser,
    required this.generated,
    required this.correctlyIdentified,
    this.sent = true,
  });

  static Message fromModel(MessageModel model, String userId) {
    return Message(
      id: model.id,
      profileId: model.senderId,
      content: model.content,
      createdAt: model.createdAt,
      sentByUser: model.senderId == userId,
      generated: model.generated,
      correctlyIdentified: model.identified,
    );
  }
}