import 'package:supabase_flutter/supabase_flutter.dart';

import '../constants.dart';
import '../models/models.dart';

class DatabaseService {
  final SupabaseClient _client; // maybe replace with client.from etc.
  /// The realtime subscription channels between two users
  /// the channels are private, and have a unique name (e.g. 'user1-user2')
  /// generated by _getChannelName
  ///
  /// The presence tracks the online/offline status
  /// In Broadcast there are two possible events:
  /// * 'message' when a message is sent
  /// * todo: 'typing' when the user or the contact is currently typing/generating
  final Map<String, RealtimeChannel> _channels = {};
  final Map<String, RealtimeChannel> _statusSubscriptions = {};
  final Map<String, RealtimeChannel> _messageSubscriptions = {};

  DatabaseService(this._client);

  void close() {
    _client.removeAllChannels();
    // _client.dispose();
  }

  /// /////////////////////////////////
  ///   PROFILE AND CONTACTS

  /// Get Username by UID

  Future<String> getUsername({required String id}) async {
    var response = await _client
        .from('profiles')
        .select('auth_id, username')
        .eq('auth_id', id)
        .single();
    return response['username'];
  }

  /// Add friend if username exists (returns friendId)

  Future<String> addFriendByUsername(
      String userId, String friendUsername) async {
    // try to get user profile
    var response = await _client
        .from('profiles')
        .select('username, auth_id')
        .eq('username', friendUsername)
        .maybeSingle();

    // Throw exception if username doesn't exist
    if (response == null) {
      throw NotFoundException('Username doesn\'t exist');
    }

    // add contact to database
    await _client
        .from('contacts')
        .insert({'sender_id': userId, 'receiver_id': response['auth_id']});

    return response['auth_id'];
  }

  /// Add a friend by UserID (/accept pending request)

  Future<void> addFriendByUUID(String userId, String friendId) async {
    await _client
        .from('contacts')
        .insert({'user_id_1': userId, 'user_id_2': friendId});
  }

  /// Fetch all contacts

  Future<List<ContactModel>> fetchContacts(String userId) async {
    // Mutuals (Friend out and Friend in)
    List? response =
        await _client.rpc('get_mutuals', params: {'user_id': userId});

    List<ContactModel> contactsMutual = response
            ?.map((entry) => ContactModel.fromJson(
                json: entry, friendIn: true, friendOut: true))
            .toList() ??
        [];

    // Outgoing friend requests (but not accepted)
    response =
        await _client.rpc('get_contacts_out', params: {'user_id': userId});

    List<ContactModel> contactsOut = response
            ?.map((entry) => ContactModel.fromJson(
                json: entry, friendIn: false, friendOut: true))
            .toList() ??
        [];

    // Ingoing friend requests (but not accepted)
    response =
        await _client.rpc('get_contacts_in', params: {'user_id': userId});

    List<ContactModel> contactsIn = response
            ?.map((entry) => ContactModel.fromJson(
                json: entry, friendIn: true, friendOut: false))
            .toList() ??
        [];

    // combine
    List<ContactModel> contacts = [
      ...contactsMutual,
      ...contactsIn,
      ...contactsOut
    ];

    return contacts;
  }

  Future<ContactModel> fetchContact(
      {required String userId, required String contactId}) async {
    try {
      List? response = await _client.rpc('get_contact',
          params: {'user_id': userId, 'cont_id': contactId});

      ContactModel result = ContactModel.fromJson(
          json: response!.first, friendIn: true, friendOut: true);

      return result;
    }

    /// ...
    catch (e) {
      rethrow;
    }
  }

  /// ///////////////////////////////////
  /// realtime

  /// set up realtime channel w contact name

  Future<void> initContactChannel({
    required String username,
    required String contactName,
  }) async {
    String channelName =
        _getChannelName(username: username, contactName: contactName);

    RealtimeChannel channel = _client.channel(
      channelName,
      opts: const RealtimeChannelConfig(
        private: true,
      ),
    );

    _channels[contactName] = channel;
  }

  void addStatusSubscription({
    required String username,
    required String contactName,
    required void Function(Map<String, dynamic> payload) statusCallback,

    /// the callback that updates the status in the chat state
    /// (whether offline or online)
    required void Function({
      required String username,
      required bool online,
    }) presenceCallback,
  }) {
    try {
      RealtimeChannel channel = _channels[contactName]!;

      // todo subscribe to broadcast on `typing` events
      RealtimeChannel subcription = channel
        ..onPresenceSync((payload) {
          /// sync

          final List<SinglePresenceState> newState = channel.presenceState();
          print('sync: $newState');
          // print('sync payload: ${newState.first}');

          // for (SinglePresenceState presence in newState) {
          //   String? name = presence.payload['username'];
          //   if (name != null) {
          //     presenceCallback(username: name, online: false); // ok
          //   }
          // }
        })
        ..onPresenceLeave((payload) {
          /// leave

          print('leave: $payload');

          for (Presence presence in payload.leftPresences) {
            String? name = presence.payload['username'];
            if (name != null) {
              presenceCallback(username: name, online: false); // ok
            }
          }
        })
        ..onPresenceJoin((payload) {
          /// join

          print('join: $payload');

          for (Presence presence in payload.newPresences) {
            String? name = presence.payload['username'];
            if (name != null) {
              presenceCallback(username: name, online: true); // ok
            }
          }
        })
        ..subscribe(
          (status, error) async {
            /// and track own status

            if (status == RealtimeSubscribeStatus.subscribed) {
              final presenceTrackStatus =
                  await channel.track({'username': username});
              print('presenceTrackStatus: $presenceTrackStatus');
            }
          },
        );

      _statusSubscriptions[contactName] = subcription;
    } catch (e) {
      print(e);

      rethrow;
    }
  }

  /// stop listening to presence (e.g. when blocked etc.)

  void removeStatusSubscription(contactName) {
    try {
      // unsubscribe and remove from map
      _statusSubscriptions[contactName]!.unsubscribe();
      _statusSubscriptions.remove(contactName);
    } catch (e) {
      print(e);
      rethrow;
    }
  }

  /// listen to messages in real time
  ///
  /// payload is json with two entries: 'username' and 'message'
  /// example:
  ///
  /// {
  ///  "username": "user1",
  ///  "message": {
  ///    "id": "1",
  ///    "sender_id": "1234-5678",
  ///    "receiver_id": "9876-5432",
  ///    "content": "hello",
  ///    "created_at": "2024-10-10T10:10:10.000Z",
  ///    "generated": null
  ///   }
  /// }

  void addMessageSubscription({
    required String username,
    required String contactName,
    required void Function(MessageModel message) messageCallback,
  }) {
    RealtimeChannel subscription = _channels[contactName]!
        .onBroadcast(
            event: 'message',
            callback: (event) {
              var payload = event['payload'];
              if (payload['username'] == username) return;
              messageCallback(MessageModel.fromJson(payload['message']));
            })
        .subscribe();

    _messageSubscriptions[contactName] = subscription;
  }

  /// stop listening to messages (i.e. when closing chat page)

  void removeMessageSubscription(String contactName) {
    try {
      // unsubscribe and remove from map
      _messageSubscriptions[contactName]!.unsubscribe();
      _messageSubscriptions.remove(contactName);
    } catch (e) {
      print(e);
      rethrow;
    }
  }

  /// broadcast a message

  /// /////////////////////////////////
  ///   MESSAGES

  /// fetch all messages for a chat room.
// maybe invert, and get latest msgs first, then invert rendering in chatroom page
// (so that not all msgs have to be loaded for large chat rooms)
  Future<List<MessageModel>> fetchMessages({
    required String userId,
    required String contactId,
  }) async {
    try {
      List<Map<String, dynamic>> response = await _client.rpc('get_messages',
          params: {'user_id': userId, 'contact_id': contactId});

      return response.map((e) => MessageModel.fromJson(e)).toList();
    }

    ///
    catch (e) {
      // todo handle specific error types
      rethrow;
    }
  }

  /// send message
  ///
  /// todo: (idea) enable sending null, to show '...' writing in progress
  /// -> (returns Future<String> of message id and then override when actually sending)

  Future<void> sendMessage({
    required String userId,
    required String contactId,
    required String content,
  }) async {
    /// Try sending
    try {
      await _client.rpc('insert_message', params: {
        'sender_id': userId,
        'receiver_id': contactId,
        'content': content,
        'generated': false,
      });
    } catch (e) {
      // todo handle specific error types
      rethrow;
    }
  }

  /// generate message
  Future<void> sendGeneratedMessage({
    required String userId,
    required String contactId,
  }) async {
    /// Try sending
    try {
      await _client.rpc('send_generated_chat_message', params: {
        'user_id': userId,
        'contact_id': contactId,
      });
    } catch (e) {
      // todo handle specific error types
      rethrow;
    }
  }

  Future<void> classifyMessage({
    required String messageId,
    required bool guess,
  }) async {
    // 1. call and await the rpc fct.
    ///
    try {
      await _client.rpc('guess_message', params: {
        'message_id': messageId,
        'guess': guess,
      });
    }

    ///
    catch (e) {
      rethrow;
    }
  }

  /// /////////////////////////////////
  ///   GENERATION SETTINGS

  /// fetch system prompt
  Future<Map<String, dynamic>> fetchSystemPrompt(String userId) async {
    /// ...
    try {
      var result = await _client
          .from('settings')
          .select('system_prompt, prompt_created_at')
          .eq('user_id', userId)
          .single();

      return result;
    }

    /// ...
    catch (e) {
      rethrow;
    }
  }

  /// update system prompt
  Future<void> updateSystemPrompt(
      {required String userId, required String prompt}) async {
    ///
    try {
      await _client
          .rpc('update_prompt', params: {'id': userId, 'prompt': prompt});
    }

    ///
    catch (e) {
      rethrow;
    }
  }

  /// reset system prompt
  Future<void> resetSystemPrompt(String userId) async {
    ///
    try {
      await _client
          .rpc('update_prompt', params: {'id': userId, 'prompt': null});
    }

    ///
    catch (e) {
      rethrow;
    }
  }

  /// /////////////////////
  /// helpers

  /// get the ordered channel name from the user names

  String _getChannelName({
    required String username,
    required String contactName,
  }) {
    // just 'username1-username2' in lex. order
    List<String> names = [username, contactName];
    names.sort((a, b) {
      return a.toLowerCase().compareTo(b.toLowerCase());
    });

    return names.join('-');
  }
}
